### ISSUE TITLE
Badges and counter over run the pull down arrow

### ISSUE THREAD

**Issue by dmanjava** [CuppaLabs/angular2-multiselect-dropdown#127]
Hello,

 I have installed angular2-multiselect-dropdown and am limiting the number of badges to show however the badges and the selected item counter over run the pull down arrow.  Screen shot is attached.  Any help you can provide is greatly appreciated.

Thank you.
Darnell

![screen shot 2018-01-03 at 1 16 32 pm](https://user-images.githubusercontent.com/20650797/34538760-f778fb8e-f08a-11e7-8aa8-b86a6d195e0e.png)

**Comment by CuppaLabs** [comment]
fix available in v2.3.0

**Comment by omkar9999** [comment]
Hi,

This issue is still observed when selected items are greater than 99

Please find attached the screenshot-
![image](https://user-images.githubusercontent.com/16288992/35824400-5cb651e8-0a78-11e8-94ab-bf06f1488838.png)
