### ISSUE TITLE
ERROR TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by hoangnguyen208** [CuppaLabs/angular2-multiselect-dropdown#133]
The error appears on line 91:
`AngularMultiSelect.prototype.ngAfterViewInit = function () {
    this._elementRef.nativeElement.getElementsByClassName("lazyContainer")[0].addEventListener('scroll', 
    this.onScroll.bind(this));
};`

From this file: 
/node_modules/angular2-multiselect-dropdown/multiselect.component.js

Version: 2.3.0

**Comment by hoangnguyen208** [comment]
The issue appears when I added `groupBy` option, when I remove it, there is no more issue

**Comment by catchshyam** [comment]
+1

Is this repo still active. I can do a pull request for this issue if it is going to be merged (I see 5 month old pull requests are still not merged)

**Comment by tomasmendesr** [comment]
+1

**Comment by juanferreras** [comment]
+1 same for me

**Comment by CuppaLabs** [comment]
fixed

**Comment by cooljeffro** [comment]
I am still experiencing this issue when using both the lazyLoading and groupBy options.
