### ISSUE TITLE
On ng build -aot getting the error Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by narayan91pati** [CuppaLabs/angular2-multiselect-dropdown#139]
/Users/**/Documents/GitHub/**/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (109,9):

*I am using CLI to import pakages. And using the latest version too. 2.3.0 @CuppaLabs @

**Comment by sudhakary** [comment]
Hi I have the same issue please resolve this issue as soon as possible

**Comment by strikerdimabel** [comment]
Hi! I have a similar problem when using angular 5.2.1 and --aot.
ERROR in node_modules\angular2-multiselect-dropdown\multiselect.component.d.ts.AngularMultiSelect.html(12,112): : The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enu
m type.

**Comment by CuppaLabs** [comment]
fixed

**Comment by ax-alex** [comment]
Hi! I'm still having this issue, using Angular 2.4.10 and your multi-select version 2.9.0. The application works flawlessly while using ng serve/cli. However, building the application results in the following six errors:
```
ERROR in E:/SAM/SAM-GUI/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (74,35): Supplied parameters do not match any signature of call target.
ERROR in E:/SAM/SAM-GUI/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (113,9): Supplied parameters do not match any signature of call target.
ERROR in E:/SAM/SAM-GUI/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (159,9): Supplied parameters do not match any signature of call target.
ERROR in E:/SAM/SAM-GUI/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (74,35): Supplied parameters do not match any signature of call target.
ERROR in E:/SAM/SAM-GUI/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (113,9): Supplied parameters do not match any signature of call target.
ERROR in E:/SAM/SAM-GUI/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (159,9): Supplied parameters do not match any signature of call target.
```
Please advice on how to resolve those errors.
Best regards,
-A.
