### ISSUE TITLE
Compile error for PROD with angular-cli

### ISSUE THREAD

**Issue by thedarkdestructor** [CuppaLabs/angular2-multiselect-dropdown#29]
Hi, 

there is a blockig bug when building with angular cli for PROD configuration

Build command: `ng build --prod`

This is the output:

```
Module not found: Error: Can't resolve 'angular2-multiselect-dropdown' in '...\angular\src\$$_gendir\app\intersection-query'
 @ ./src/$$_gendir/app/intersection-query/intersection-query.component.ngfactory.ts 18:0-53
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts[39m[22m
```

Maybe is related to [this problem](https://github.com/angular/angular-cli/issues/1465 ) ? 

**This is a blocking issue for us.**

Thanks in advance for your support.

**Comment by thedarkdestructor** [comment]
I've continued my search and the problem seems related to AOT compilation that kicks in only with -prod build.

https://github.com/angular/angular-cli/issues/5733
https://github.com/angular/angular-cli/issues/7113

With the new version of angular-cli  the variables that are private and need to be accessed in templates are no more accessible: they need to be changed to to public. Is this the case?

**Comment by thedarkdestructor** [comment]
I've continued my search and the problem seems related to AOT compilation that kicks in only with -prod build.

angular/angular-cli#5733
angular/angular-cli#7113

With the new version of angular-cli the variables that are private and need to be accessed in templates are no more accessible: they need to be changed to to public. Is this the case?

**Comment by CuppaLabs** [comment]
fixed in v1.2.4

**Comment by thedarkdestructor** [comment]
That is great! Thank you for your quick action. Integrated the new version and works like a charm.

**Comment by mhalttu** [comment]
@CuppaLabs I am using @angular/cli version 1.3.2 and I still have the same problem. Am I misunderstanding something?

**Comment by CuppaLabs** [comment]
@mhalttu Do you mean angular-cli v1.3.2 ?

**Comment by mhalttu** [comment]
Ah, apologies. I was googling about the problem and did not realize I was in a different project.

**Comment by wakawaka54** [comment]
Okay so how again are we suppose to figure out where the problem is if we have a:

ERROR in C:/.../src/$$_gendir/app/app.module.ngfactory.ts (159,52): Supplied parameters do not match any signature of call target.

??? Can we somehow keep the $$_gendir around? Is there some log file that it spits out? I have no clue what it is complaining about and I've spent about 5 hours looking through all the code and there is a lot of it.

**Comment by CuppaLabs** [comment]
@wakawaka54 : How are you importing the component package ? systemjs ? webpack ? or cli ?
