### ISSUE TITLE
Search issue with lazyLoading (v3.1.0)

### ISSUE THREAD

**Issue by DejanNemet** [CuppaLabs/angular2-multiselect-dropdown#296]
Hello,

When **lazyLoading: true** search doesn't work if the dropdown contains allot of entries (600+ in my case). Selecting anything works as long as I don't type into search. As soon as I type anything into search I get this
![image](https://user-images.githubusercontent.com/23314429/45611234-04345c80-ba5f-11e8-9c17-927002207829.png)

If **lazyLoading: false** then all entries continue to run outside the dropdown
![image](https://user-images.githubusercontent.com/23314429/45611074-75274480-ba5e-11e8-8aed-4bee10974dfc.png)

These errors don't happen on my other dropdown that has 20-30 entries.

**Comment by DejanNemet** [comment]
- Update -
After building for production I get this error (could be related to the issue above):

ERROR in : Type VirtualScrollComponent in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts is part of the declarations of 2 modules: AngularMultiSelectModule in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/multiselect.component.d.ts and VirtualScrollModule in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts! Please consider moving VirtualScrollComponent in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts to a higher module that imports AngularMultiSelectModule in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/multiselect.component.d.ts and VirtualScrollModule
in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts. You can also create a new NgModule that exports and includes VirtualScrollComponent in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts then import that NgModule in AngularMultiSelectModule in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/multiselect.component.d.ts and VirtualScrollModule in C:/Projects/project01/node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts.

**Comment by CuppaLabs** [comment]
@DejanNemet Fixed. Please use v3.1.1

**Comment by DejanNemet** [comment]
Sorry, didn't realise that. Thank you very much. I'll wait for the next release.

**Comment by CuppaLabs** [comment]
Fixed. please use v3.2.1

**Comment by kundanln** [comment]
how to update v3.2.1

**Comment by MD2500** [comment]
Issue still exists in v4.2.1 - lazyLoading: true search doesn't work if the dropdown contains a huge (4000+) dataset list; works ok on another with 996 entries

**Comment by poojashah2419** [comment]
I am facing same issue , my search is not at all working for any of the data .  if anyone has solution please provide

**Comment by eb-arun** [comment]
@CuppaLabs , I am also facing the same issue on search not working for any of my dropdown when lazy loading is enabled. Please respond with a fix.
Version: 4.6.3

**Comment by poojashah2419** [comment]
I found the solution . Here is a logic to append data when getting from lazy loading
 let newData = [];
        for (const list of dataList) {
          newData.push({ 'id': list['id'], 'itemName': list['id'] ,'type':list['type'] , 'description':list['description']});
        }
        this.arrData = this.arrData.concat(newData);

**Comment by eb-arun** [comment]
@poojashah2419 , i am getting data lazy loaded while scrolling, but the issue is when try to search the filter its return nothing, just showing noDataLabel. Do you have any fix for filter>search function to work as expected ?

**Comment by poojashah2419** [comment]
@eb-arun  yes , I am talking about that only. First when you get data use below code 
let newData = [];
for (const list of dataList) {
newData.push({ 'id': list['id'], 'itemName': list['id'] ,'type':list['type'] , 'description':list['description']});
}
Here this.arrData is a source which you will pass to component. After scrolling when you get data from API / by any method , again use same above code to append new data to your data source. So the case is that is the only way to append new data to current source which will fix your search filter not working issue. concat method. Its bit wiered solution but I used it and it fixed search result .
